import { MapDifficulty, MapSize } from './map.js';

export interface Scenario {
  readonly name: string;
  readonly description: string;
  readonly fileName: string;
  readonly size: MapSize;
  readonly difficulty: MapDifficulty;
}

export const scenarios: readonly Scenario[] = [
  {
    description: 'The Griffons will protect you until you are ready to make your move.',
    difficulty: MapDifficulty.Easy,
    fileName: 'AES31000.MAP',
    name: 'Claw ( Easy )',
    size: MapSize.Small,
  },
  {
    description: 'Many islands make up this area, each with its own rewards and obstacles.',
    difficulty: MapDifficulty.Easy,
    fileName: 'BEM20234.MAP',
    name: 'Archipelago',
    size: MapSize.Medium,
  },
  {
    description: 'A large island of tight passes with a circular feel',
    difficulty: MapDifficulty.Normal,
    fileName: 'CNM51234.MAP',
    name: 'Around the Bay',
    size: MapSize.Medium,
  },
  {
    description: 'A treacherous place difficult to navigate. Much to be gained far from home.',
    difficulty: MapDifficulty.Normal,
    fileName: 'DNL31234.MAP',
    name: 'Badlands',
    size: MapSize.Large,
  },
  {
    description: 'A small island where the action starts quickly. Watch your back!',
    difficulty: MapDifficulty.Normal,
    fileName: 'ENS11234.MAP',
    name: 'Close Quarters',
    size: MapSize.Small,
  },
  {
    description: 'Wide open spaces where the harsh lands of the West meet the fertile lands of the East.',
    difficulty: MapDifficulty.Easy,
    fileName: 'FEL60234.MAP',
    name: 'Continentia',
    size: MapSize.Large,
  },
  {
    description: "You're the center of attention with little time to prepare. Good luck, you'll need it.",
    difficulty: MapDifficulty.Tough,
    fileName: 'GHM41000.MAP',
    name: 'Crossroads',
    size: MapSize.Medium,
  },
  {
    description: 'A large island of mostly desert is lush and plentiful along its shore.',
    difficulty: MapDifficulty.Normal,
    fileName: 'HNM11234.MAP',
    name: 'Desert Isle',
    size: MapSize.Medium,
  },
  {
    description: 'The enemy is in sight! The Dragons of the pass will keep the peace, but for how long?',
    difficulty: MapDifficulty.Normal,
    fileName: 'INM61234.MAP',
    name: 'Dragon Pass',
    size: MapSize.Medium,
  },
  {
    description: 'An island of your own is a good start, but control of the mainland is the key to success.',
    difficulty: MapDifficulty.Easy,
    fileName: 'JEM70234.MAP',
    name: 'Four Corners',
    size: MapSize.Medium,
  },
  {
    description: 'Stranded on this island, the four kingdoms have divided the area.',
    difficulty: MapDifficulty.Normal,
    fileName: 'KNS21234.MAP',
    name: 'Four Nations',
    size: MapSize.Small,
  },
  {
    description: 'An exotic place rich with resources and hidden treasure caches.',
    difficulty: MapDifficulty.Normal,
    fileName: 'LNS41234.MAP',
    name: "Hermit's Isle",
    size: MapSize.Small,
  },
  {
    description: 'This scenario seems Impossible to win. Can you conquer the Jolly Roger?',
    difficulty: MapDifficulty.Impossible,
    fileName: 'MIS71200.MAP',
    name: 'Jolly Roger',
    size: MapSize.Small,
  },
  {
    description: 'Invading Knights spare 3 of your towns and agree to peace talks at your castle.',
    difficulty: MapDifficulty.Tough,
    fileName: 'NHL51000.MAP',
    name: 'Knights Quest',
    size: MapSize.Large,
  },
  {
    description: 'The mountain passes are important. The bridge is the key between East and West.',
    difficulty: MapDifficulty.Normal,
    fileName: 'ONL71234.MAP',
    name: 'Land Bridge',
    size: MapSize.Large,
  },
  {
    description: 'Open spaces and guarded passes make up this dangerous, challenging area.',
    difficulty: MapDifficulty.Normal,
    fileName: 'PNM31234.MAP',
    name: 'Pathways',
    size: MapSize.Medium,
  },
  {
    description: 'An area rich in resources and treasure known for its ease of travel by both land and sea.',
    difficulty: MapDifficulty.Normal,
    fileName: 'QNL11234.MAP',
    name: 'Rivers End',
    size: MapSize.Large,
  },
  {
    description: 'A place of great mystery.  Legend tells of a hidden yet inaccessable treasure cache.',
    difficulty: MapDifficulty.Normal,
    fileName: 'RNL41234.MAP',
    name: 'Shangri-La',
    size: MapSize.Large,
  },
  {
    description: 'Much to explore and many treasures. The greatest danger lies close to home.',
    difficulty: MapDifficulty.Easy,
    fileName: 'SEL21234.MAP',
    name: 'Squirrel Lake',
    size: MapSize.Large,
  },
  {
    description: 'Surrounded, outmatched, and undersupplied. Can you survive the Jester?',
    difficulty: MapDifficulty.Tough,
    fileName: 'THS51000.MAP',
    name: 'The Jester',
    size: MapSize.Small,
  },
  {
    description: 'A small island seems easy... Until they arrive!',
    difficulty: MapDifficulty.Tough,
    fileName: 'UHS61200.MAP',
    name: 'Two if by Sea',
    size: MapSize.Small,
  },
  {
    description: 'The desert holds great wealth for those who can brave it. Follow the Bedouin trails...',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95A1234.MAP',
    name: 'Arabian Nights',
    size: MapSize.Medium,
  },
  {
    description: "A thriving continent. But why is that volcano rumbling... and what's this about a secret?",
    difficulty: MapDifficulty.Normal,
    fileName: 'W95B1234.MAP',
    name: 'Atlantis',
    size: MapSize.Small,
  },
  {
    description: "The pathways keep you safe, but you'll need to take risks to conquer this marshy land.",
    difficulty: MapDifficulty.Normal,
    fileName: 'W95C1234.MAP',
    name: 'Bayou',
    size: MapSize.Large,
  },
  {
    description: "Three brothers fight for their father's kingdom, and an old rival takes advantage.",
    difficulty: MapDifficulty.Tough,
    fileName: 'W95D1234.MAP',
    name: 'Civil War',
    size: MapSize.Medium,
  },
  {
    description: 'A massive conflict. Four large empires separated by heavily defended neutrals.',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95E1000.MAP',
    name: 'Empires At War',
    size: MapSize.Large,
  },
  {
    description: 'Fire Island is said to hold the riches of the land.',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95F1234.MAP',
    name: 'Fire Island',
    size: MapSize.Large,
  },
  {
    description: 'Four nations fight for the remains of a fallen empire.',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95G1234.MAP',
    name: 'Ghost Town',
    size: MapSize.Medium,
  },
  {
    description: 'A strangely familiar land...',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95H1234.MAP',
    name: 'GringoLand',
    size: MapSize.Large,
  },
  {
    description: 'Rule the waves to rule Britannia!!!',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95I1234.MAP',
    name: 'Hail Britannia',
    size: MapSize.Small,
  },
  {
    description: 'The fastest victory can lie on the outer edges, but power comes from the center.',
    difficulty: MapDifficulty.Easy,
    fileName: 'W95J1234.MAP',
    name: 'New World',
    size: MapSize.Small,
  },
  {
    description: "They say the grass is greener on the other side, but you'll have to get there to find out!",
    difficulty: MapDifficulty.Normal,
    fileName: 'W95K1234.MAP',
    name: 'Neighbors',
    size: MapSize.Medium,
  },
  {
    description: 'Four Warlocks duel in a specially constructed arena of magic.',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95L1234.MAP',
    name: 'The Arena',
    size: MapSize.Small,
  },
  {
    description: 'Lots of reasources make this a quick start but a tough finish.', // TODO: reasources?
    difficulty: MapDifficulty.Normal,
    fileName: 'W95M1234.MAP',
    name: 'The Sound',
    size: MapSize.Large,
  },
  {
    description: 'No boats... How will you get around?',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95N1234.MAP',
    name: 'Safe Corners?',
    size: MapSize.Medium,
  },
  {
    description: 'A favorite vacation resort for all the fashionable ogres and trolls.',
    difficulty: MapDifficulty.Normal,
    fileName: 'W95O1234.MAP',
    name: 'Sea Breeze',
    size: MapSize.Medium,
  },
  {
    description: "The towns have all the neat stuff, but don't ignore the rougher terrains!",
    difficulty: MapDifficulty.Normal,
    fileName: 'W95P1234.MAP',
    name: 'Town Haul',
    size: MapSize.Medium,
  },
];
